### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by raulazo-m** [danielwilczak101/EasyGA#22]
Hello! when I import the package I get the following error:

`Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-26ee7e822105>", line 1, in <module>
    import EasyGA

  File "/usr/local/lib/python3.6/dist-packages/EasyGA/__init__.py", line 2, in <module>
    from .EasyGA import GA

  File "/usr/local/lib/python3.6/dist-packages/EasyGA/EasyGA.py", line 1
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined`

any suggestions?

**Comment by danielwilczak101** [comment]
Hey @raulazo-m,

EasyGA doesn't support python 3.6 because of it's backend features. I recommend downloading python 3.9.7 or greater.
