### ISSUE TITLE
issue installing easyga

### ISSUE THREAD

**Issue by drmichaelscherger** [danielwilczak101/EasyGA#25]
Hello,

I am getting the following error messages while installing EasyGA.  I wanted to try this package...  I am using:
Anaconda
Python 3.12

I was able to install it for python 3.9.  I did not test any other versions.  Please consider working on this as the current version of python is 12.

Thanks in advance.

(ga) [mscherger@hpclogin:~/GA]$ pip3 install easyga
Collecting easyga
  Downloading EasyGA-1.6.1-py3-none-any.whl.metadata (4.7 kB)
Collecting matplotlib~=3.3.2 (from easyga)
  Downloading matplotlib-3.3.4.tar.gz (37.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 89.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w4ea946f/matplotlib_ea8f3a9dc04141c68ae4bb09949af58f/setup.py", line 52, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-w4ea946f/matplotlib_ea8f3a9dc04141c68ae4bb09949af58f/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-w4ea946f/matplotlib_ea8f3a9dc04141c68ae4bb09949af58f/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-w4ea946f/matplotlib_ea8f3a9dc04141c68ae4bb09949af58f/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(ga) [mscherger@hpclogin:~/GA]$

**Comment by RafaelBarbosatec** [comment]
same here
